# Generated by Django 4.0 on 2021-12-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shartnoma_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=10)),
                ('tolov_oyi', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('Jule', 'Jule'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=15)),
                ('chegirma_status', models.CharField(default="yo'q", max_length=10)),
                ('ch_sababi', models.CharField(max_length=50)),
                ('ch_miqdori', models.PositiveIntegerField()),
                ('t_sanasi', models.DateField()),
                ('kassir', models.CharField(max_length=30)),
                ('tolashi_lozim', models.PositiveIntegerField()),
                ('naqd', models.PositiveIntegerField()),
                ('bank', models.PositiveIntegerField()),
                ('plastik', models.PositiveIntegerField()),
                ('click', models.PositiveIntegerField()),
                ('jami_toladi', models.PositiveIntegerField()),
                ('jami_qoldi', models.PositiveIntegerField()),
                ('kurs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shartnoma_app.kurs')),
                ('shartnoma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shartnoma_app.shartnoma')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shartnoma_app.student')),
                ('ustoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shartnoma_app.ustoz')),
            ],
        ),
    ]
